import { NextResponse } from 'next/server';
import pool from '@/lib/db';
import bcrypt from 'bcrypt';
import AdminAuth from '@/lib/auth/admin-auth';
import { collectErrors, checkEmail, checkRequired, checkPassword, checkSaudiMobile } from '@/lib/validators';

export async function POST(req) {
    try {
        const body = await req.json();
        const {
            email,
            password,
            first_name,
            last_name,
            position,
            phone,
            bank_user_id // ID of the existing bank entity
        } = body;

        // Validate input before any DB work.
        const { valid, firstError } = collectErrors({
            email: () => checkEmail(email),
            first_name: () => checkRequired(first_name, 'First name'),
            last_name: () => checkRequired(last_name, 'Last name'),
            bank_user_id: () => checkRequired(bank_user_id, 'Bank'),
            // Password is optional (auto-generated when blank), but if supplied must be valid.
            password: () => (password ? checkPassword(password) : null),
            // Phone is optional, but if supplied must be a valid Saudi mobile.
            phone: () => (phone ? checkSaudiMobile(phone, { label: 'Phone' }) : null),
        });
        if (!valid) {
            return NextResponse.json({ success: false, error: firstError }, { status: 400 });
        }

        // Validate admin authentication
        const adminToken = req.cookies.get('admin_token')?.value;
        if (!adminToken) {
            return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
        }

        const sessionValidation = await AdminAuth.validateAdminSession(adminToken);
        if (!sessionValidation.valid) {
            return NextResponse.json({ 
                success: false, 
                error: sessionValidation.error || 'Invalid admin session' 
            }, { status: 401 });
        }

        const client = await pool.connectWithRetry(2, 1000, 'app_api_admin_users_create-bank-employee_route.jsx_route');
        try {
            await client.query('BEGIN');

            // 1. Verify the bank entity exists and get its information
            const bankCheck = await client.query(
                `SELECT u.user_id, u.entity_name, bu.logo_url FROM users u 
                 LEFT JOIN bank_users bu ON u.user_id = bu.user_id 
                 WHERE u.user_id = $1 AND u.user_type = 'bank_user'`,
                [bank_user_id]
            );

            if (bankCheck.rowCount === 0) {
                await client.query('ROLLBACK');
                return NextResponse.json(
                    { success: false, error: 'Bank entity not found' },
                    { status: 404 }
                );
            }

            const bankEntity = bankCheck.rows[0];

            // 2. Check if user already exists
            const existingUser = await client.query(
                `SELECT user_id FROM users WHERE email = $1`,
                [email]
            );

            if (existingUser.rowCount > 0) {
                await client.query('ROLLBACK');
                return NextResponse.json(
                    { success: false, error: 'User with this email already exists' },
                    { status: 409 }
                );
            }

            // 3. Determine the effective password (trim to avoid trailing-whitespace
            //    mismatches between what is hashed here and what the user later types).
            //    Login also trims, so the stored hash and the login attempt align.
            const effectivePassword = (password || 'TempPassword123!').trim();
            const wasAutoGenerated = !password;
            const saltRounds = 10;
            const hashedPassword = await bcrypt.hash(effectivePassword, saltRounds);

            // 4. Create user record with user_type = 'bank_employee'
            const userRes = await client.query(
                `INSERT INTO users (email, password, user_type, entity_name, account_status, created_at, updated_at)
                 VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
                 RETURNING user_id`,
                [email, hashedPassword, 'bank_employee', bankEntity.entity_name, 'active']
            );
            const user_id = userRes.rows[0].user_id;

            // 5. Create bank employee record
            const employeeRes = await client.query(
                `INSERT INTO bank_employees (
                    bank_user_id, 
                    user_id, 
                    first_name, 
                    last_name, 
                    position, 
                    phone, 
                    created_at
                )
                 VALUES ($1, $2, $3, $4, $5, $6, NOW())
                 RETURNING employee_id`,
                [
                    bank_user_id,
                    user_id,
                    first_name,
                    last_name,
                    position || null,
                    phone || null
                ]
            );

            const employee_id = employeeRes.rows[0].employee_id;

            // 6. Log the action in audit log
            await client.query(
                `INSERT INTO bank_employee_audit_log (
                    employee_id, 
                    bank_user_id, 
                    action_type, 
                    action_details, 
                    ip_address
                ) VALUES ($1, $2, $3, $4, $5)`,
                [
                    employee_id,
                    bank_user_id,
                    'account_created',
                    `Bank employee account created by admin for ${email}`,
                    req.headers.get('x-forwarded-for') || req.headers.get('x-real-ip') || 'unknown'
                ]
            );

            await client.query('COMMIT');

            return NextResponse.json({
                success: true,
                message: 'Bank employee created successfully',
                data: {
                    employee_id,
                    user_id,
                    email,
                    first_name,
                    last_name,
                    position,
                    phone,
                    bank_user_id,
                    bank_entity_name: bankEntity.entity_name,
                    bank_logo_url: bankEntity.logo_url,
                    created_at: new Date().toISOString(),
                    // Always surface the exact credential that was hashed so the admin can
                    // log in immediately — whether they typed it or it was auto-generated.
                    // (Fixes the "login fails until password reset" bug: previously the
                    // real password was never shown when the admin supplied one.)
                    login_email: email,
                    login_password: effectivePassword,
                    password_auto_generated: wasAutoGenerated,
                    password_note: wasAutoGenerated
                        ? 'A password was auto-generated. Share these credentials with the employee; they can log in immediately.'
                        : 'Share these credentials with the employee; they can log in immediately.'
                }
            });

        } catch (err) {
            await client.query('ROLLBACK');
            console.error('Database transaction failed:', err);
            return NextResponse.json(
                { success: false, error: 'Failed to create bank employee' },
                { status: 500 }
            );
        } finally {
            client.release();
        }

    } catch (err) {
        console.error('Unexpected error:', err);
        return NextResponse.json(
            { success: false, error: 'Internal server error' },
            { status: 500 }
        );
    }
}
